export const industries = [
  "Software Development",
  "Technology",
  "Finance",
  "Healthcare",
  "Education",
  "Retail",
  "Manufacturing",
  "Government",
  "Consulting",
  "Telecommunications",
  "Energy",
  "Marketing & Advertising",
  "Media & Entertainment",
  "Hospitality & Tourism",
  "Real Estate",
  "Transportation & Logistics",
  "Legal Services",
  "Non-Profit & NGO",
  "Pharmaceuticals",
  "Aerospace & Defense",
  "Agriculture",
  "Construction",
  "E-commerce",
  "Insurance",
  "Automotive",
];

export const industryTopics = {
  "Software Development": [
    "Frontend Development",
    "Backend Development",
    "Full Stack Development",
    "React.js",
    "Angular",
    "Vue.js",
    "Node.js",
    "Python Development",
    "Java Development",
    "Mobile Development (iOS/Android)",
    "DevOps",
    "Database Administration",
    "System Architecture",
    "Microservices",
    "API Development",
    "Software Testing & QA",
    "Agile/Scrum Methodology",
    "Git & Version Control",
  ],
  Technology: [
    "AI & Machine Learning",
    "Cybersecurity",
    "Cloud Computing",
    "Data Science",
    "Big Data Analytics",
    "Blockchain",
    "IoT (Internet of Things)",
    "Network Administration",
    "IT Support",
    "Systems Engineering",
    "Product Management",
    "UX/UI Design",
    "Technical Writing",
    "Business Intelligence",
    "Automation & RPA",
  ],
  Finance: [
    "Investment Banking",
    "Financial Analysis",
    "Accounting",
    "Risk Management",
    "Portfolio Management",
    "Corporate Finance",
    "Financial Planning",
    "Tax Preparation",
    "Audit",
    "Trading & Securities",
    "Wealth Management",
    "Credit Analysis",
    "Compliance",
    "FinTech",
  ],
  Healthcare: [
    "Medical Research",
    "Healthcare Administration",
    "Nursing",
    "Clinical Practice",
    "Medical Coding",
    "Healthcare IT",
    "Pharmacy",
    "Physical Therapy",
    "Medical Imaging",
    "Patient Care",
    "Public Health",
    "Mental Health Services",
    "Healthcare Compliance",
  ],
  Education: [
    "Teaching",
    "Curriculum Development",
    "Educational Technology",
    "School Administration",
    "Special Education",
    "Adult Learning",
    "Online Education",
    "Instructional Design",
    "Academic Advising",
    "Educational Assessment",
  ],
  Retail: [
    "Sales",
    "Merchandising",
    "Customer Service",
    "Store Management",
    "Visual Merchandising",
    "Inventory Management",
    "Retail Buying",
    "Loss Prevention",
    "E-commerce Operations",
  ],
  Manufacturing: [
    "Production Management",
    "Quality Control",
    "Supply Chain Management",
    "Lean Manufacturing",
    "Operations Management",
    "Industrial Engineering",
    "Process Improvement",
    "Safety Management",
    "Maintenance & Repair",
    "Procurement",
  ],
  Government: [
    "Public Policy",
    "Administration",
    "Law Enforcement",
    "Public Relations",
    "Urban Planning",
    "Social Services",
    "Emergency Management",
    "Regulatory Compliance",
    "Public Finance",
  ],
  Consulting: [
    "Management Consulting",
    "IT Consulting",
    "Strategy Consulting",
    "HR Consulting",
    "Financial Consulting",
    "Marketing Consulting",
    "Operations Consulting",
    "Change Management",
  ],
  Telecommunications: [
    "Network Engineering",
    "Telecom Sales",
    "Customer Support",
    "Network Planning",
    "Wireless Communications",
    "Fiber Optics",
    "VoIP Technology",
    "5G Technology",
  ],
  Energy: [
    "Renewable Energy",
    "Oil & Gas",
    "Energy Management",
    "Solar Technology",
    "Wind Energy",
    "Energy Trading",
    "Power Generation",
    "Energy Efficiency",
    "Nuclear Energy",
  ],
  "Marketing & Advertising": [
    "Digital Marketing",
    "Content Marketing",
    "Social Media Marketing",
    "SEO/SEM",
    "Brand Management",
    "Market Research",
    "Creative Direction",
    "Media Planning",
    "Email Marketing",
    "Influencer Marketing",
    "Growth Marketing",
  ],
  "Media & Entertainment": [
    "Film Production",
    "Journalism",
    "Broadcasting",
    "Content Creation",
    "Video Editing",
    "Music Production",
    "Game Development",
    "Animation",
    "Public Relations",
  ],
  "Hospitality & Tourism": [
    "Hotel Management",
    "Restaurant Management",
    "Event Planning",
    "Travel Agency",
    "Tourism Marketing",
    "Front Desk Operations",
    "Food & Beverage Management",
    "Catering",
  ],
  "Real Estate": [
    "Property Management",
    "Real Estate Sales",
    "Commercial Real Estate",
    "Property Development",
    "Real Estate Investment",
    "Leasing",
    "Real Estate Marketing",
  ],
  "Transportation & Logistics": [
    "Supply Chain Logistics",
    "Fleet Management",
    "Warehouse Operations",
    "Freight Management",
    "Distribution",
    "Route Optimization",
    "Inventory Planning",
  ],
  "Legal Services": [
    "Corporate Law",
    "Litigation",
    "Legal Research",
    "Paralegal Services",
    "Intellectual Property",
    "Contract Law",
    "Compliance",
    "Legal Technology",
  ],
  "Non-Profit & NGO": [
    "Program Management",
    "Fundraising",
    "Grant Writing",
    "Community Outreach",
    "Volunteer Coordination",
    "Advocacy",
    "International Development",
  ],
  Pharmaceuticals: [
    "Drug Development",
    "Clinical Trials",
    "Regulatory Affairs",
    "Quality Assurance",
    "Medical Sales",
    "Pharmacovigilance",
    "Research & Development",
  ],
  "Aerospace & Defense": [
    "Aerospace Engineering",
    "Defense Systems",
    "Avionics",
    "Systems Integration",
    "Quality Assurance",
    "Project Management",
  ],
  Agriculture: [
    "Crop Management",
    "Agricultural Technology",
    "Farm Management",
    "Food Safety",
    "Agricultural Research",
    "Sustainable Agriculture",
  ],
  Construction: [
    "Project Management",
    "Civil Engineering",
    "Construction Management",
    "Site Supervision",
    "Estimation",
    "Safety Management",
    "Architecture",
  ],
  "E-commerce": [
    "Online Marketplace Management",
    "Digital Product Management",
    "Conversion Optimization",
    "Customer Experience",
    "Fulfillment Operations",
    "E-commerce Analytics",
  ],
  Insurance: [
    "Underwriting",
    "Claims Processing",
    "Risk Assessment",
    "Insurance Sales",
    "Actuarial Science",
    "Policy Administration",
  ],
  Automotive: [
    "Automotive Engineering",
    "Vehicle Manufacturing",
    "Quality Control",
    "Automotive Sales",
    "Service & Maintenance",
    "Supply Chain",
  ],
};

export const interviewTypes = [
  "Technical",
  "Behavioral",
  "Case Study",
  "In-Person",
];

export const interviewDifficulties = [
  "Internship",
  "Entry Level",
  "Mid Level",
  "Senior Level",
  "Exec Level",
];
